name: Build to Site

on: 
  push:
    branches: 
      - master
env:
  HAS_BUILD_FILES: false
jobs:
  build:
    runs-on: macos-latest
    strategy:
       matrix:
          node-version: [12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check files
        id: check_js_step
        run: js_files=$(find js -maxdepth 1 -type f)
             echo "::set-env name=HAS_BUILD_FILES::$([ -z "$js_files" ] || echo true)"
      
      - name: Log env var
        run:  echo "::warning ::HAS_BUILD_FILES=${{env.HAS_BUILD_FILES}}"
      
      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ env.HAS_BUILD_FILES == true }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Build project
        if: ${{ env.HAS_BUILD_FILES == true }}
        run: yarn install
             yarn run build_js
      
      - name: Move and name directory
        if: ${{ env.HAS_BUILD_FILES == true }}
        run: cp -r build current
