name: Update Docs Site
on:
  push:
    branches:
    - ghpages
    paths:
    - 'js/**.js'
jobs:
  build:
    name: Compile and Push
  steps:
    - name: compile js
      run: babel
    - name: push to unjustio
      run: node build_docs.js
