name: Update Docs Site
on:
  push:
    branches:
    - gh-pages
    paths:
    - 'js/**.js'
jobs:
  build:
    name: Compile and Push
    runs-on: ubuntu-latest
    steps:
      - name: compile js
        run: babel
