name: Node.js CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    if: github.event.pull_request.merged
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Build project
      run: yarn run build_js
    - name: Move and name directory
      run: cp -r build current
