name: Node.js CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Check if js build needed
      id: check_js_step
      run: echo "::set-output name=has_js_files::'(find js -maxdepth 1 -type f)''"
    - name: Checkout code
      if: steps.check_js_step.outputs.has_js_files == 'false'
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - name: Build project
      run: yarn run build_js
    - name: Move and name directory
      run: cp -r build current
